site_name: Citrix NetScaler SD-WAN Center 10.0 NITRO API Documentation
site_description: Citrix NetScaler SD-WAN Center 10.0 NITRO API Documentation
site_title: Developer Docs

# Copyright
copyright: 'Copyright &copy; 1999-2019 Citrix Systems, Inc. All rights reserved. '

extra_css:
  - 'assets/stylesheets/extra.css'

# Configuration
theme:
  name: null
  custom_dir: devdocs-theme

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  feature:
    tabs: false
  palette:
    primary: white
    accent: blue
  font: false
  favicon: /media/favicon.ico
  logo: https://developer-docs.citrix.com/_static/Citrix_Logo_Black.png

# Customization
extra:
  social:
    - type: youtube
      link: https://www.youtube.com/channel/UCiOupk9QF6jdk3EDKTHDykA
    - type: github-alt
      link: https://github.com/citrix
    - type: twitter
      link: https://twitter.com/citrixdeveloper
    - type: linkedin
      link: https://www.linkedin.com/company/citrix/

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - footnotes
  - meta
  - extra

# Page tree
nav:
 - Getting Started Guide: index.md
 - Configuration:
   - login: login.md
   - regions: regions.md
 - Reports:
   - sites: sites.md
   - services: services.md
   - virtual_paths: virtual_paths.md
   - paths: paths.md
   - applications: applications.md
   - hdx: hdx.md
   - wan_links: wan_links.md
   - mpls_queues: mpls_queues.md
   - gre_tunnels: gre_tunnels.md
   - ipsec_tunnels: ipsec_tunnels.md
   - classes: classes.md
   - mos_scores: mos_scores.md
   - ethernet_interfaces: ethernet_interfaces.md
   - events: events.md
   - top_application_families: top_application_families.md
   - top_sites: top_sites.md
 - Custom Objects:
   - meta_data: meta_data.md
 - Error Messages: error-messages.md
